### ISSUE TITLE
Metrics not showing

### ISSUE THREAD

**Issue by kikisp** [amelbakry/kdave-chart#2]
Hey Ahmed
Thanks for this useful chart..we deployed it successfully ..pods are running logs are showing:

```
[2022-07-29 23:17:45,572| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,509| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,530| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
```
so i guess its working?

Metrics are showing in prometheus:
```
# HELP wf_k8s_deprecated_versions_job_info Deprecated API versions Job information
# TYPE wf_k8s_deprecated_versions_job_info gauge
wf_k8s_deprecated_versions_job_info{duration_seconds="",last_run="2022-07-29T23:17:35"} 1.0
# HELP wf_k8s_deprecated_versions_info Deprecated API versions
# TYPE wf_k8s_deprecated_versions_info gauge
# HELP wf_k8s_deployed_releases Total number of the deployed releases
# TYPE wf_k8s_deployed_releases gauge
wf_k8s_deployed_releases 0.0
# HELP wf_k8s_deployed_releases_with_deprecated_api_version Total number of the deployed releases that have deprecated apiVersions
# TYPE wf_k8s_deployed_releases_with_deprecated_api_version gauge
wf_k8s_deployed_releases_with_deprecated_api_version 0.0
# HELP wf_k8s_deployed_releases_with_removed_api_version Total number of the deployed releases that have removed apiVersions
# TYPE wf_k8s_deployed_releases_with_removed_api_version gauge
wf_k8s_deployed_releases_with_removed_api_version 0.0
```
As you can see metrics are not showing any deprecations
and we for sure have some deprecated api-s..
are we doing something wrong or maybe its a bug?
Thank you

**Comment by amelbakry** [comment]
Hey Stefan,

Looks like you are using helm v3? if it's the case, please provide the helm binary as helm3 in your values file https://github.com/amelbakry/kdave-chart/blob/main/values.yaml#L85-L86 otherwise it'll try to collect the deployed helmv2 releases and thus no deprecated api is found

Thanks

**Comment by kikisp** [comment]
Thanks for fast answer..Yea we are using helm 3 for deploys..
here is a snippet from our deployment yaml
```
  deployment:
    automountServiceAccountToken: true
    containers:
      imageRepository: aelbakry
      imageName: kdave-server
      imageTag: 1.0.2
      args:
        - --data-file=/app/data/data.json
        - --helm-binary=helm3
      volumeMounts:
        - name: kdave-exporter-volume
          mountPath: /app/data/
    securityContext:
      runAsUser: 1003
      runAsGroup: 1003
    volumes:
      - name: kdave-exporter-volume
        persistentVolumeClaim:
          claimName: kdave-exporter-pvc-kdave-data
```
so i guess its already there

**Comment by amelbakry** [comment]
Well, have you tried to use the kdave CLI to verify and check any random release to see if it uses deprecated apiVersions or not? Also, what apiVersion for which object do you think it's deprecated and it's not shown in kdave. Could you please provide an example, might be kdave deprecation policy https://github.com/wayfair-incubator/kdave/blob/main/config/versions.yaml needs to be updated

**Comment by kikisp** [comment]
to be honest running kdave cli locally wasnt posible because of access issues to our clusters.
but i can share report from other tool..in this case pluto
<img width="774" alt="Screenshot 2022-08-01 at 12 24 40" src="https://user-images.githubusercontent.com/4484226/182128690-491db4e5-2c11-4398-bc71-5a16898ffc4b.png">

**Comment by amelbakry** [comment]
Looks like it's a permission issue for kdave while it's running in your cluster.
from your first comment `wf_k8s_deployed_releases 0.0` kdave is not able to see any deployed release, so it makes sense that there are no deprecated apiVersions.
You can test this in a local kind cluster to narrow down the issue and if it's didn't work, I can replicate your kind cluster setup and see what's wrong

**Comment by kikisp** [comment]
Yea but i am not seeing and issues in pod logs..No mentions of permissions or something like that ..
other thing that i noticed is that adding --debug to args breaks kdave..i get pod error that says no such flag.

**Comment by amelbakry** [comment]
You're right, ignore that. If it's a permission issue, the pod will fail and we'll have something in the logs.
But still, the problem is that it's not able to see any deployed release in the cluster

Can you share the end of the logs of the kdave pod, also how many releases in the cluster (it may be still running and checking if the number of releases are high and the metrics will be updated at the end)

**Comment by amelbakry** [comment]
If these are the end of the logs in the kdave pod
```
[2022-07-29 23:17:45,572| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,509| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
[2022-07-29 23:17:46,530| INFO| helm-handler] Checking the used apiVersions for release: xxxxxxxx
```
This means the job is still running and the metrics will be updated once the job is done

**Comment by kikisp** [comment]
Nope this are a the head of the log so at the start .. now i am seeing just a lots of:
`[2022-08-01 11:14:51] "GET /metrics HTTP/1.1" 200 1083 0.002011` prometheus scraping metrics..
we dont have too much releases it is definitely finished by now..
i have a feeling thats something related to helm3.. i can try to deploy something with helm 2 and see if it will get picked up

**Comment by amelbakry** [comment]
When the job is done, you should see some logs similar to these
```
[2022-08-01 02:45:41,709| INFO| helm-handler] Data file is outdated or doesn't exist. Building a new data file
[2022-08-01 02:45:41,709| INFO| helm-handler] Writing data to data file: data/data.json
```
After that, the metrics will be updated
If you see these entries in the logs `GET /metrics` doesn't mean the job is finished

**Comment by kikisp** [comment]
oh i didnt saw those ..
```
args:
        - --data-file=/app/data/data.json
        - --helm-binary=helm3
      volumeMounts:
        - name: kdave-exporter-volume
          mountPath: /app/data/
    securityContext:
      runAsUser: 1003
      runAsGroup: 1003
    volumes:
      - name: kdave-exporter-volume
        persistentVolumeClaim:
          claimName: kdave-exporter-pvc-kdave-data
   ```
   maybe my volume setup is wrong and it cant write..but than i guess i would find something in logs about not able to write to fle
   i doubt that it takes so much time to finish.. i deploy it like on friday..
